site_name: Lista de tarefas
repo_url: https://github.com/GuilhermeKulkamp/tasklist
repo_name: GuilhermeKulkamp/tasklist
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/style.css